### ISSUE TITLE
Not working with next.js

### ISSUE THREAD

**Issue by ronihcohen** [frappe/charts#56]
#### Expected Behaviour
I was trying to run this example: https://github.com/tobiaslins/frappe-charts-react-example 
with next.js.

#### Actual Behaviour

``` _frappeCharts2.default is not a constructor

_frappeCharts2.default is not a constructor
TypeError: _frappeCharts2.default is not a constructor
    at Chart.componentDidMount (http://localhost:3000/_next/1510152164727/page/:45412:19)
    at Chart.proxiedComponentDidMount (http://localhost:3000/_next/1510152164727/main.js:16882:40)
    at commitLifeCycles (http://localhost:3000/_next/1510152164727/commons.js:11511:24)
    at commitAllLifeCycles (http://localhost:3000/_next/1510152164727/commons.js:12300:9)
    at HTMLUnknownElement.callCallback (http://localhost:3000/_next/1510152164727/commons.js:1305:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/_next/1510152164727/commons.js:1344:16)
    at invokeGuardedCallback (http://localhost:3000/_next/1510152164727/commons.js:1201:27)
    at commitAllWork (http://localhost:3000/_next/1510152164727/commons.js:12421:9)
    at workLoop (http://localhost:3000/_next/1510152164727/commons.js:12693:13)
    at HTMLUnknownElement.callCallback (http://localhost:3000/_next/1510152164727/commons.js:1305:14)
```

https://github.com/ronihcohen/frappe-charts-next-example

Frappé Charts version:

^0.0.4

**Comment by pratu16x7** [comment]
@tobiaslins Would you like to take a look?

**Comment by tobiaslins** [comment]
hi @ronihcohen 

Can you please share more details?
- What did you exactly import?
- Please show me your package.json

**Comment by ronihcohen** [comment]
@tobiaslins You can find my example here: https://github.com/ronihcohen/frappe-charts-next-example

**Comment by pratu16x7** [comment]
Seems like an import problem; check the module path on line:
https://github.com/tobiaslins/frappe-charts-react-example/blob/master/src/chart.js#L3

with the one in your rep:
https://github.com/ronihcohen/frappe-charts-next-example/blob/master/components/chart.js#L3

**Comment by ronihcohen** [comment]
@tobiaslins  still not working :-( 
```
Unexpected token export
/Users/ronihacohen/Web/frappe-charts-next-example/node_modules/frappe-charts/dist/frappe-charts.min.esm.js:3270
export default Chart;
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Module._compile (/Users/ronihacohen/Web/frappe-charts-next-example/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
```
Also I would update the README.md https://github.com/tobiaslins/frappe-charts-react-example/blob/master/README.md with the proper import.

**Comment by tobiaslins** [comment]
@ronihcohen I thought nextjs does the transpiling

**Comment by pratu16x7** [comment]
Not a `next.js` expert here. Closing as not a project-specific issue. Feel free to open in case of updates.

**Comment by arangates** [comment]
Still exists

**Comment by ideashower** [comment]
@arangates I was able to get this to work by specifying a relative path (see: https://github.com/vercel/next.js/issues/883).

ie `../node_modules/frappe-charts/dist/frappe-charts.min.esm`
